:: Batch File for Filling database with data
python bb_cli.py add_coach "Kaipo Rozwolf#9628, Rozwolf, "
python bb_cli.py add_coach "Mephistopheles#1345, GaaHL, "
python bb_cli.py add_coach "Hammish#1754, DarkHammish, "
python bb_cli.py add_coach "Remi#2160, Remillard, "
python bb_cli.py add_coach "ook#1656, Tirrskll, "
python bb_cli.py add_coach "Tyre#3203, Tyreesae, "
python bb_cli.py add_coach "Jinxer Boss#2228, Dylan Scissell, "
python bb_cli.py add_coach "FleurDeMur#1942, FleurDeMur, "
python bb_cli.py add_coach "Yldren#5532, Yldren, "
python bb_cli.py add_coach "thedjally#4556, thedjally, "
python bb_cli.py add_coach "Kailindo#4852, Bthulhu Dunes, "
python bb_cli.py add_coach "Rende#4526, Rende, "
python bb_cli.py add_coach "Humbdinger#1030, Humbdinger, "
python bb_cli.py add_team "Kaipo Rozwolf#9628, Waxaklahun Ubah Kan, Lizardmen, 2"
python bb_cli.py add_team "Mephistopheles#1345, Kaiserschlact, Necromantic, 2"
python bb_cli.py add_team "Hammish#1754, Doomhammeriffic, Norse, 2"
python bb_cli.py add_team "Remi#2160, K-Tel Records - The 80s!, Norse, 2"
python bb_cli.py add_team "ook#1656, Better to Hear You With, Elven Union, 2"
python bb_cli.py add_team "Tyre#3203, For the Greater Eats, Ogres, 2"
python bb_cli.py add_team "Jinxer Boss#2228, Spooky Scary Skeletons, Khemri, 2"
python bb_cli.py add_team "Fleur, FL Men, Lizard, 2"
python bb_cli.py add_team "Yldren#5532, Betty's Borises, Dark Elves, 2"
python bb_cli.py add_team "thedjally#4556, Twitch's Terrors, Skaven, 2"
python bb_cli.py add_team "Kailindo#4852, Ogrimmar Saurfangs, Orcs, 2"
python bb_cli.py add_team "Rende#4526, The Harmless Princesses, Chaos, 2"
python bb_cli.py add_team "Humbdinger#1030, Cottage Cheese Fanatics, Vampires, 2"
python bb_cli.py add_tour "Superb Owl XXXLVI, Round Robin, 2, 14, 13"
