# BB2-Discord-Bot
A Discord Bot for handling casual Blood Bowl 2 tournament information

## TODO
* List all games -- CLI Only
* List all games in the current week -- CLI and Bot -- DONE!
* List all games for a team across all weeks
* List all teams -- CLI Only
* Add teams -- CLI Only
* Delete teams -- CLI Only
* Update teams -- CLI Only
* Update schedule -- CLI Only
* Add game results -- CLI Only
* Implement trivia selector and trivia file -- CLI and Bot -- DONE!
* Implement silly dice rolling method for the Bot -- DONE!
* Implement Discord API Bot -- DONE!

## Thanks and Attribution
The bulk of the trivia file was taken from the
[Lore of Nuffle](http://loreofnuffle.talkfantasyfootball.org/) where many of
the sourcebook tidbits has been compiled (along with additions.)  Many thanks
to Ithilkir of TalkFantasyFootball forums for putting that together (along with
Khenian and Torpor of same).  I tried to get a hold of Ithilkir at the forums
however the site would not mail me the "email verification" after several
attempts so I have given up for now.  Hopefully attribution will be
sufficient!  Also many thanks to Games Workshop for a fun tactical (and silly)
football variant!

